### ISSUE TITLE
[sheet] 各ページのタイトル決め

### ISSUE THREAD

**Issue by MaxMEllon** [SLP-KBIT/ETR2015#8]

**Comment by kattsun17** [comment]
1.要求分析
　ユースケース図で各ケースを書く
　要求の定義をする
2.構造設計
　クラス図とか
3.振る舞い
　シーケンス図とか
4.要素技術
5.....

こんな感じでいかがでしょうか?
名前はまた違っても良いかと思いますが...
また順番は変わっても良いと思います。

**Comment by MaxMEllon** [comment]
課題が拔けてない？

**Comment by MaxMEllon** [comment]
`2.` はなんかパッと見わかりにく気がしました！
プログラムの構造と設計方針 とかのほうがわかりやすそ！

**Comment by kattsun17** [comment]
すいませ、
5に課題を入れればとおもいます!

**Comment by kattsun17** [comment]
1.何をつくるか
2.俺達のぷろぐらむ
3.こうやって動くぜ
4.研究してみた
5.課題に取り組み

**Comment by kattsun17** [comment]
こういう方向もありかなと...

**Comment by MaxMEllon** [comment]
Dropbox:/etr_2015/model/sheet/concept/PageTitleList.txt
